sonar.projectKey=painel
sonar.projectName=painel
sonar.projectVersion=1.0

# 🧠 Lista de pastas onde o código PHP está
sonar.sources=.

# 🔗 URL do servidor SonarQube
sonar.host.url=http://localhost:9000

# 🔐 Seu token de autenticação (substitua aqui)
sonar.token=sqp_b1a04417c1399c1ca01098d34bd3592df6f29e6a

# 🌐 Ignorar arquivos desnecessários
sonar.exclusions=**/vendor/**,**/*.min.js,**/node_modules/**,**/*.map

# sqp_03c2adc6927a5f626b178cf6b2c141c47704d780

